apiVersion: v1
kind: Service
metadata:
  name: umami-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: umami
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30060
      targetPort: 30060
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: umami-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`umami.hauptmann.dev`)
      middlewares:
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: umami-external
          port: 30060
          passHostHeader: true
  tls:
    certResolver: cloudflare
