apiVersion: v1
kind: Service
metadata:
  name: immich-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: immich
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30041
      targetPort: 30041
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immichq-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.philippmhauptmann.me`)
      kind: Rule
      services:
        - name: immich-external
          port: 30041
          passHostHeader: true
  tls:
    certResolver: cloudflare
