apiVersion: v1
kind: Service
metadata:
  name: paperless-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: paperless
spec:
  ports:
    - port: 30070
      targetPort: 30070
      protocol: TCP
      name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: paperless-external-1
  namespace: traefik
  labels:
    app.kubernetes.io/name: paperless
    kubernetes.io/service-name: paperless-external
    endpointslice.kubernetes.io/managed-by: argocd
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 30070
endpoints:
  - addresses:
      - 192.168.0.129
    conditions: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.hauptmann.dev`)
      middlewares:
        - name: default-secure-chain
      kind: Rule
      services:
        - name: paperless-external
          port: 30070
          passHostHeader: true
  tls:
    store:
      name: default
