apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: jellyfin-external
  namespace: traefik
spec:
  servers:
    - url: "http://192.168.0.129:30013"
  passHostHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.meinheim.de`)
      kind: Rule
      services:
        - name: jellyfin-external
          kind: TraefikService
  tls:
    certResolver: cloudflare