#-------------------------------------------------------------------------------
# Service: JELLYFIN
#-------------------------------------------------------------------------------

# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: truenas-jellyfin
#   namespace: traefik
#   annotations:
#     traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
# spec:
#   entryPoints:
#     - websecure
#   routes:
#     - match: Host(`jellyfin.philippmhauptmann.me`)
#       kind: Rule
#       middlewares:
#         - name: secure-headers
#         - name: ratelimit
#         - name: cloudflare-ip-whitelist
#       services:
#         - name: jellyfin-external
#           kind: TraefikService
# ---
# apiVersion: traefik.io/v1alpha1
# kind: TraefikService
# metadata:
#   name: jellyfin-external
#   namespace: traefik
# spec:
#   serversLoadBalancer:
#     servers:
#       - url: http://192.168.0.129:30013
# ---

#-------------------------------------------------------------------------------
# Service: IMMICH
#-------------------------------------------------------------------------------



#-------------------------------------------------------------------------------
# Service: JELLYSEERR
#-------------------------------------------------------------------------------

# Jellyseerr Service


#-------------------------------------------------------------------------------
# Service: RADARR
#-------------------------------------------------------------------------------

# radarr Service
apiVersion: v1
kind: Service
metadata:
  name: truenas-radarr
  namespace: traefik
spec:
  ports:
    - port: 8081
      targetPort: 30025
      protocol: TCP
  type: ClusterIP
---
# radarr Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-radarr
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30025
        protocol: TCP
---
# radarr IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-radarr
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-radarr
          port: 8081
---

#-------------------------------------------------------------------------------
# Service: PAPERLESS
#-------------------------------------------------------------------------------

# Paperless Service
apiVersion: v1
kind: Service
metadata:
  name: truenas-paperless
  namespace: traefik
spec:
  ports:
    - port: 8083
      targetPort: 30070
      protocol: TCP
  type: ClusterIP
---
# Paperless Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-paperless
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30070
        protocol: TCP
---
# Paperless IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-paperless
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`paperless.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist

      services:
        - name: truenas-paperless
          port: 8083
---

#-------------------------------------------------------------------------------
# Service: AUTHENTIK
#-------------------------------------------------------------------------------

# Authentik Service
apiVersion: v1
kind: Service
metadata:
  name: truenas-authentik
  namespace: traefik
spec:
  ports:
    - port: 8089
      targetPort: 30140
      protocol: TCP
  type: ClusterIP
---
# Authentik Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-authentik
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30140
        protocol: TCP
---
# Authentik IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-authentik
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-authentik
          port: 8089
---

#-------------------------------------------------------------------------------
# Service: N8N
#-------------------------------------------------------------------------------

# N8n Service
apiVersion: v1
kind: Service
metadata:
  name: truenas-n8n
  namespace: traefik
spec:
  ports:
    - port: 8091
      targetPort: 30109
      protocol: TCP
  type: ClusterIP
---
# N8n Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-n8n
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30109
        protocol: TCP
---
# N8n IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-n8n
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`n8n.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-n8n
          port: 8091
---

#-------------------------------------------------------------------------------
# Service: NEXTCLOUD
#-------------------------------------------------------------------------------

# nextcloud service
apiVersion: v1
kind: Service
metadata:
  name: truenas-nextcloud
  namespace: traefik
spec:
  ports:
    - port: 8093
      targetPort: 30056
      protocol: TCP
  type: ClusterIP
---
# nextcloud Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-nextcloud
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30056
        protocol: TCP
---
# nextcloud IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-nextcloud
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nc.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-nextcloud
          port: 8093
---

#-------------------------------------------------------------------------------
# Service: SONARR
#-------------------------------------------------------------------------------

# sonarr service
apiVersion: v1
kind: Service
metadata:
  name: truenas-sonarr
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  ports:
    - port: 8093
      targetPort: 30113
      protocol: TCP
  type: ClusterIP
---
# sonarr Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-sonarr
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30113
        protocol: TCP
---
# sonarr IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-sonarr
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sonarr.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-sonarr
          port: 8093
---

#-------------------------------------------------------------------------------
# Service: BOOKSTACK
#-------------------------------------------------------------------------------

# bookstack service
apiVersion: v1
kind: Service
metadata:
  name: truenas-bookstack
  namespace: traefik
spec:
  ports:
    - port: 8095
      targetPort: 30214
      protocol: TCP
  type: ClusterIP
---
# bookstack Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-bookstack
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30214
        protocol: TCP
---
# bookstack IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-bookstack
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`bookstack.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-bookstack
          port: 8095
---

#-------------------------------------------------------------------------------
# Service: GITEA
#-------------------------------------------------------------------------------

# gitea service
apiVersion: v1
kind: Service
metadata:
  name: truenas-gitea
  namespace: traefik
spec:
  ports:
    - port: 8096
      targetPort: 30008
      protocol: TCP
  type: ClusterIP
---
# gitea Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: truenas-gitea
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.0.129
    ports:
      - port: 30008
        protocol: TCP
---
# git IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: truenas-gitea
  namespace: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`git.philippmhauptmann.me`)
      middlewares:
        - name: secure-headers
        - name: ratelimit
        - name: cloudflare-ip-whitelist
      services:
        - name: truenas-gitea
          port: 8096
