apiVersion: v1
kind: Service
metadata:
  name: paperless-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: paperless
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30070
      targetPort: 30070
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.philippmhauptmann.me`)
      kind: Rule
      services:
        - name: paperless-external
          port: 30070
          passHostHeader: true
  tls:
    certResolver: cloudflare
