 TraefikService: Weighted RR für Jellyfin
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: jellyfin-external
  namespace: traefik
spec:
  weighted:
    services:
      - name: jellyfin-external-direct
        kind: TraefikService

# TraefikService: Direktes Backend für Jellyfin
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: jellyfin-external-direct
  namespace: traefik
spec:
  servers:
    - url: "http://192.168.0.129:30013"
  passHostHeader: true

# IngressRoute: Leitet Traffic zu Jellyfin über TraefikService
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`jellyfin.example.com`)
      kind: Rule
      services:
        - name: jellyfin-external
          kind: TraefikService
  tls:
    certResolver: cloudflare
