apiVersion: v1
kind: Service
metadata:
  name: dockhand-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: dockhand
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30328
      targetPort: 30328
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: dockhand-upstream-transport
  namespace: traefik
spec:
  serverName: truenas.hauptmann.dev
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dockhand-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dockhand.hauptmann.dev`)
      middlewares:
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: dockhand-external
          port: 30328
          scheme: https
          serversTransport: dockhand-upstream-transport
          passHostHeader: true
  tls:
    store:
      name: default
