apiVersion: v1
kind: Service
metadata:
  name: seerr-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: seerr
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30357
      targetPort: 30357
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: seerr-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`seerr.hauptmann.dev`)
      middlewares:
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: seerr-external
          port: 30357
          passHostHeader: true
  tls:
    store:
      name: default
