apiVersion: v1
kind: Service
metadata:
  name: jellystat-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: jellystat
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30176
      targetPort: 30176
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellystat-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellystat.hauptmann.dev`)
      middlewares:
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: jellystat-external
          port: 30176
          passHostHeader: true
