# -----------------------------------------------------------------------------
# Namespace: traefik
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    istio.io/dataplane-mode: ambient

---
# -----------------------------------------------------------------------------
# Traefik Service
# -----------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    istio: ingressgateway
    app: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: 8000
      protocol: TCP
    - name: websecure
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
