env:
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: CF_DNS_API_TOKEN

certificatesResolvers:
  cloudflare:
    acme:
      email: "haupha08@gmail.com"
      storage: /data/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  kubernetesCRD:
    allowExternalNameServices: true
    allowCrossNamespace: true

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    http:
      encodedCharacters:
        allowEncodedSlash: true
        # allowEncodedBackSlash: true
        # allowEncodedNullCharacter: true
        # allowEncodedSemicolon: true
        # allowEncodedPercent: true
        allowEncodedQuestionMark: true
        # allowEncodedHash: true
      tls:
        certResolver: cloudflare
      options: default@kubernetescrd

tlsStore:
  default:
    defaultCertificate:
      secretName: cloudflare-origin-cert
    defaultGeneratedCert:
      resolver: cloudflare
      domain:
        main: hauptmann.dev
        sans:
          - '*.hauptmann.dev'

logs:
  general:
    format: json
    level: INFO
  access:
    enabled: true
    format: json
    fields:
      headers:
        defaultmode: keep

metrics:
  prometheus:
    service:
      enabled: true
    disableAPICheck: false
    serviceMonitor:
      enabled: true
      metricRelabelings:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: nodename
          replacement: $1
          action: replace
      jobLabel: traefik
      interval: 30s
      honorLabels: true
      additionalLabels:
        release: kube-prometheus-stack
    headerLabels:
      user_id: X-User-Id
      tenant: X-Tenant

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteMany
  size: 128Mi
  path: /data
  storageClass: longhorn

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

podSecurityContext:
  runAsGroup: 65532
  runAsUser: 65532
  runAsNonRoot: true
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"

service:
  enabled: true
  type: LoadBalancer
  annotations:
    kube-vip.io/loadbalancerIPs: "192.168.0.140"
  spec:
    loadBalancerIP: "192.168.0.140"
  
