# yamllint disable rule:line-length
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: portfolio-updater-dev
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: pmhme-portfolio-dev
      images:
        - alias: pmhme
          imageName: ghcr.io/mainman94/pmhme
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.-]+)?(?:\+[a-zA-Z0-9.-]+)?$
            forceUpdate: false
            pullSecret: pullsecret:argocd/ghcr-pull-pat
        - alias: contact-api
          imageName: ghcr.io/mainman94/contact-api
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.-]+)?(?:\+[a-zA-Z0-9.-]+)?$
            forceUpdate: false
            pullSecret: pullsecret:argocd/ghcr-pull-pat
        - alias: notifier-telegram
          imageName: ghcr.io/mainman94/notifier-telegram
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.-]+)?(?:\+[a-zA-Z0-9.-]+)?$
            forceUpdate: false
            pullSecret: pullsecret:argocd/ghcr-pull-pat
        - alias: notifier-email
          imageName: ghcr.io/mainman94/notifier-email
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.-]+)?(?:\+[a-zA-Z0-9.-]+)?$
            forceUpdate: false
            pullSecret: pullsecret:argocd/ghcr-pull-pat
  writeBackConfig:
    method: "git:secret:argocd/git-credentials"
    gitConfig:
      repository: "https://github.com/mainman94/multi-k8s-infra"
      branch: "main"
      writeBackTarget: "kustomization:/eggenberg-talos-cluster-1/argocd-apps-configuration/pmhme/overlays/dev"
      # yamllint enable rule:line-length
