apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
- ../../base
images:
- name: dockerha08/pmhme
  newTag: "20260128181707"
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Rollout
    name: portfolio-app
