apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
  - ../../base
images:
  - name: dockerha08/pmhme
    newTag: d5040d2370821112322a59dc1568b03f27ef5ed8
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Rollout
      name: portfolio-app
