---
# yamllint disable rule:line-length
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAjiEn/rUyyz1ZiwgNbdjTikbvYonbZhAqV0G9/SDnsmRMf0SEvHBiljuRBAcWKEEw3ovoyNx+W1XtSXpaN9BAyCazGOCFWuJEvPFYiCCyUGXtB9JQkOlCRlUd9pAZBYbtuF6eINZYZhFQudI9G5rIMY6pczxwz9e5FraYljkZ5x8pjns4W4DIGFjKnfwybHWHqQa07/EQkR8yexhUkWpMPSD/AkF2+PZJmPKZqS8pDedxVM7j3EZxYiyjoFaghoWz7vcX4RP+BxRVZILGfnpdOH+a0geK6llYDQo9s+6yuNStRZK+lEMT0CktSOeWN7dhtjVq+S50ikCKGIevFZ7/d030uNGtOEmN8OWvXFD7TZzpxZes45HWKrjJ1/DcE4Buzra5Mx0rNopfTimx1levy5NIO5rCuMcmskRlpPjY1BFw6nSm3DLJrNbY7of7FXjX1ieb4DJy13LhjqLlTtb3irZy1YIWsEmt42oo18g5CbzBmI77MEaNv4dzEKhg9nOWW+Xk0lncoVY0Aej5P6QXHNED1wNGraUw7FJfjahTmc5SOGDDfv61n2ZWcuEXRJ8ezeTriToeEMiOwbGWnzj7O48viOuzESQQDUG/71CemcGuncqfY30vanopLjsuPaarbA2ssL8ifjPSl2XRHydebXkJcQrFUgX1Ky9zOY7GiL02Vf+OeXSWEm/kYoe3riG4sF2yVuaAPtvPexMjkRq1M5g==
    client_secret: AgBe8uho6SXee80X9e/tbBBOMkH6N3m891QL1tj7TJqphw32zoZSZznkp68wwNdXTuyLKejABDWHjfH3Bs8QgxYgcg8MGW+NL1IvhnmQ/wH9j4U7L7YBv67eI5BcHlfrqKutWLQZlEbljenj3/26UNQY0yutUmIXBwJVhzagJC25COV3oe3lb52pqmi2ocu0+9CPpxMfIVS2hvU2hopiPRqREet9YcUhrFMxmafA5H+JLSVXcU0LriyvOgUIWTYD1NyFilVXNzTGT/qlf7qImqP9REqfkDXrQGoP9awa3vGY1UizziqG1tm/PcTYoNF91P5H5h+a4vFTfXJ+7/K+Pgs5EbPU+yIXhpRYcjjquVJZXz/REaK+0apc9FjX7UbAQtT/FfYtmRydFkfDNfP6Pz7C85SPnBYub1af4hlGMypX0LIjGZgrVeHecYYJvIDk/gTactHbIdbZYXrtjN6WqDmq4MDKwFcfnJ/cbc6rRhpPW7fzeIRugt63s8+nVZ04GV7E6qs9j8oCW5rk99mKCE1ttmmz8/JWsWXmG73HbLh4VD/Ne/QIL1+Gv4jGitlcTq0lZL/Mml47KyNP7rINPhr/YDAmBUPxRFLp8PLKuCdzBsHbkrEISIVatJ+YtZ/mwHTAANmdVRXaqRDhpz/V8zirb/ZcE1YFGlWIPU02Kd8ywf1PNF/nVxqHnkCWwDBjTeF82GqlyKiwLCSktiexPHjCIeiUd8fa86bD/94YaMdhMDK5EgBMwEEzIEfplobk/gQYSHZUfU0hFtYi1xtjkv4=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
# yamllint enable rule:line-length
