# kube-vip Helm Chart values
# https://kube-vip.io/docs/installation/helm/

# Virtual IP for the control-plane API server.
config:
  # TODO: Set this to the desired API VIP if different.
  address: "192.168.0.140"

# Environment flags for kube-vip
# See: https://kube-vip.io/docs/installation/flags/
env:
  # TODO: Set the actual host interface that should hold the VIP (e.g. eth0, ens18).
  vip_interface: "enp0s31f6"
  vip_arp: "true"
  vip_subnet: "24"
  lb_port: "6443"

  # Control-plane VIP
  cp_enable: "true"
  vip_leaderelection: "true"

  # Disable kube-vip service load-balancer to avoid conflicts with Cilium LB.
  lb_enable: "true"
  svc_enable: "true"
  svc_election: "true"

  prometheus_server: ":2112"

podMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
