defaultSettings:
  defaultReplicaCount: "1"

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

ingress:
  enabled: false

csi:
  attacherReplicaCount: "1"
  provisionerReplicaCount: "1"
  resizerReplicaCount: "1"
  snapshotterReplicaCount: "1"
