apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.19.1
      helm:
        valueFiles:
          - $values/eggenberg-reverse-proxy-cluster/argocd-apps-configuration/cert-manager/values.yaml
    - repoURL: https://github.com/mainman94/multi-k8s-infra/
      path: "eggenberg-reverse-proxy-cluster/argocd-apps-configuration/cert-manager"
      targetRevision: HEAD
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
