api:
  replicas: 1
  host: kargo.hauptmann.dev
  adminAccount:
    enabled: false
  argocd:
    urls:
      "": "https://argocd.hauptmann.dev"
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    tls:
      enabled: false
  tls:
    enabled: false

controller:
  replicas: 1
  argocd:
    namespace: argocd
    watchArgocdNamespaceOnly: false

webhooksServer:
  replicas: 1

managementController:
  replicas: 1
