api:
  replicas: 1
  adminAccount:
    enabled: false
  argocd:
    urls:
      - "https://argocd.hauptmann.dev"
    namespace: argocd
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: kargo.hauptmann.dev
        paths:
          - /
    tls:
      enabled: false
  tls:
    enabled: false

controller:
  replicas: 1
  argocd:
    namespace: argocd
    watchArgocdNamespaceOnly: false

webhooksServer:
  replicas: 1

externalWebhooksServer:
  tls:
    enabled: false

managementController:
  replicas: 1
