apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-creds
  namespace: portfolio-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: gitea-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: image
      data:
        repoURL: git.hauptmann.dev/philipphauptmann/.*
        repoURLIsRegex: "true"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: prod/gitea
        metadataPolicy: None
        property: PACKAGE_USERNAME
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: prod/gitea
        metadataPolicy: None
        property: PACKAGE_PAT
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-creds
  namespace: portfolio-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: github-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        repoURL: https://github.com/mainman94/multi-k8s-infra.git
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: prod/github
        metadataPolicy: None
        property: USERNAME
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: prod/github
        metadataPolicy: None
        property: PAT
