apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: portfolio-kargo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: portfolio-kargo
  namespace: portfolio-kargo
spec:
  promotionPolicies:
    - stageSelector:
        name: test
      autoPromotionEnabled: true
    - stageSelector:
        name: prod
      autoPromotionEnabled: true
