apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: pmhme-portfolio
  namespace: pmhme-portfolio
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/mainman94/multi-k8s-infra.git
        branch: main
        commitSelectionStrategy: NewestFromBranch
        includePaths:
          - eggenberg-talos-cluster-1/argocd-apps-configuration/pmhme/overlays/dev/kustomization.yaml
    - image:
        repoURL: dockerha08/pmhme
        imageSelectionStrategy: SemVer
        allowTags: '^[0-9]+\.[0-9]+\.[0-9]+(?:-[a-zA-Z0-9.-]+)?(?:\+[a-zA-Z0-9.-]+)?$'
        discoveryLimit: 5
