apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: pmhme-portfolio
spec:
  vars:
    - name: gitRepo
      value: https://github.com/mainman94/multi-k8s-infra
    - name: imageRepo
      value: dockerha08/pmhme
    - name: repoPath
      value: ./repo
    - name: overlayPath
      value: eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/test
    - name: appName
      value: pmhme-portfolio-test
  requestedFreight:
    - origin:
        kind: Warehouse
        name: pmhme-portfolio
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ${{ vars.repoPath }}
        - uses: http
          as: smoke-http-200
          retry:
            timeout: 2m0s
          config:
            method: GET
            url: https://dev.hauptmann.dev/
            successExpression: response.status == 200
        - uses: http
          as: version-check
          retry:
            timeout: 15m0s
          config:
            method: GET
            url: https://dev.hauptmann.dev/version
            successExpression: response.status == 200 && response.body.version == commitFrom(vars.gitRepo).ID
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ${{ vars.repoPath }}/${{ vars.overlayPath }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ quote(commitFrom(vars.gitRepo).ID) }}
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.repoPath }}
            message: ${{ outputs['update-image'].commitMessage }}
        - uses: git-push
          config:
            path: ${{ vars.repoPath }}

