apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: pmhme-portfolio
spec:
  vars:
    - name: gitRepo
      value: https://github.com/mainman94/multi-k8s-infra
    - name: repoPath
      value: ./repo
  requestedFreight:
    - origin:
        kind: Warehouse
        name: pmhme-portfolio
      sources:
        direct: true
        autoPromotionOptions:
          selectionPolicy: NewestFreight
  verification:
    analysisTemplates:
      - name: pmhme-portfolio-http-check
    args:
      - name: service-name
        value: portfolio-service
      - name: namespace
        value: portfolio-dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ${{ vars.repoPath }}
