apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: pmhme-portfolio
  namespace: pmhme-portfolio
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/mainman94/multi-k8s-infra
        branch: main
        includePaths:
          - eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/dev
