apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kube-vip.github.io/helm-charts
      chart: kube-vip
      targetRevision: 0.9.8
      helm:
        valueFiles:
          - $values/eggenberg-reverse-proxy-cluster/argocd-apps-configuration/kube-vip/values.yaml
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
