ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: uptime.hauptmann.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudflare-origin-cert
      hosts:
        - uptime.hauptmann.dev
persistence:
  enabled: true
  storageClass: "longhorn"
  #accessMode: ReadWriteOnce

nscd:
  enabled: true

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
