# EventBus - required for Argo Events communication
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argocd
spec:
  nats:
    native:
      replicas: 3
      auth: token
