api:
  replicas: 1
  host: kargo.hauptmann.dev
  secret:
    name: kargo-admin-secret
  adminAccount:
    enabled: true
  argocd:
    urls:
      "": "https://argo-rp.hauptmann.dev"
  ingress:
    enabled: true
    ingressClassName: cilium
    tls:
      enabled: false
  tls:
    enabled: false
controller:
  replicas: 1
  argocd:
    namespace: argocd
    watchArgocdNamespaceOnly: false
webhooksServer:
  replicas: 1
managementController:
  replicas: 1
