# Alertmanager configuration
alertmanager:
  enabled: true
  service:
    type: ClusterIP
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          storageClassName: longhorn
# Prometheus server configuration
prometheus:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
    ingressClassName: cilium
    hosts:
      - monitoring.hauptmann.dev
    paths:
      - /
    pathType: Prefix
  # yamllint disable rule:line-length
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
          storageClassName: longhorn
    additionalScrapeConfigs:
      - job_name: "ztunnel"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
            action: keep
            regex: istio-system;ztunnel
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: http-monitoring
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: instance
# yamllint enable rule:line-length
# Grafana configuration
grafana:
  enabled: true
  ingress:
    enabled: false
  # RWO longhorn volume: old pod must release the PV before the new one can attach
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: longhorn
# Node Exporter configuration
nodeExporter:
  enabled: true
# Kube State Metrics configuration
kubeStateMetrics:
  enabled: true
