apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical-secrets-operator
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-graz
        envSlug: prod
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical-secrets-operator
      creationPolicy: "managed"
    - secretName: cloudflare-api-token
      secretNamespace: traefik
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          CF_DNS_API_TOKEN: "{{ .CLOUDFLARE_API_KEY.Value }}"
    - secretName: cloudflare-tunnel-secret
      secretNamespace: cloudflared
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          credentials.json: |-
            {
              "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_ID.Value }}",
              "TunnelID": "{{ .CLOUDFLARE_TUNNEL_STRASSGANG_ID.Value }}",
              "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_STRASSGANG_SECRET.Value }}"
            }
          cert.pem: "{{ .CLOUDFLARE_TUNNEL_STRASSGANG_CERTIFICATE.Value }}"
    - secretName: seaweedfs-s3-secret
      secretNamespace: seaweedfs
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        stringData:
          seaweedfs_s3_config: '{"identities":[{"name":"{{ .SEAWEEDFS_ADMIN_NAME.Value }}","credentials":[{"accessKey":"{{ .SEAWEEDFS_ADMIN_ACCESS_KEY.Value }}","secretKey":"{{ .SEAWEEDFS_ADMIN_SECRET_KEY.Value }}"}],"actions":["Admin","Read","Write"]},{"name":"{{ .SEAWEEDFS_READONLY_NAME.Value }}","credentials":[{"accessKey":"{{ .SEAWEEDFS_READONLY_ACCESS_KEY.Value }}","secretKey":"{{ .SEAWEEDFS_READONLY_SECRET_KEY.Value }}"}],"actions":["Read"]}]}'
