defaultSettings:
  defaultReplicaCount: "2"
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
ingress:
  enabled: false
#csi:
  #attacherReplicaCount: "1"
  #provisionerReplicaCount: "1"
  #resizerReplicaCount: "1"
  #snapshotterReplicaCount: "1"
