apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmhme-kargo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mainman94/multi-k8s-infra
    targetRevision: HEAD
    path: eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/kargo
  destination:
    server: https://kubernetes.default.svc
    namespace: pmhme
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
