# yamllint disable rule:line-length
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pmhme-portfolio-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      path: "eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/production"
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      name: portfolio-app
      namespace: portfolio
      jsonPointers:
        - /spec/template/spec/containers/0/resources
# yamllint enable rule:line-length
