apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical-secrets-operator
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: HomeLab
        projectId: <project-id>
        envSlug: prod
        secretsPath: "<secrets-path>"
        # secretName: <secret-name> # optional, falls nur ein Secret synchronisiert werden soll
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical-secrets-operator
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          NEW_KEY_NAME: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"
          KEY_WITH_BINARY_VALUE: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"
