apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical-secrets-operator
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-graz
        envSlug: prod
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical-secrets-operator
      creationPolicy: "managed"
    - secretName: cloudflare-api-token
      secretNamespace: traefik
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          CF_DNS_API_TOKEN: "{{ .CLOUDFLARE_API_KEY.Value }}"
    - secretName: docker-pull-secret
      secretNamespace: portfolio
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          docker-pull-secret: "{{ .DOCKER_PULL_SECRET.Value }}"
