apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical-secrets-operator
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-graz
        envSlug: prod
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical-secrets-operator
      creationPolicy: "managed"
    - secretName: cloudflare-api-token
      secretNamespace: traefik
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          CF_DNS_API_TOKEN: "{{ .CLOUDFLARE_API_KEY.Value }}"
    - secretName: docker-pull-secret
      secretNamespace: portfolio
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          .dockerconfigjson: "{{ .DOCKER_PULL_SECRET.Value }}"
    - secretName: cloudflare-tunnel-secret
      secretNamespace: cloudflared
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          credentials.json: |-
            {
              "AccountTag": "{{ .CLOUDFLARE_ACCOUNT_ID.Value }}",
              "TunnelID": "{{ .CLOUDFLARE_TUNNEL_EGGENBERG_ID.Value }}",
              "TunnelSecret": "{{ .CLOUDFLARE_TUNNEL_EGGENBERG_SECRET.Value }}"
            }
          cert.pem: "{{ .CLOUDFLARE_TUNNEL_EGGENBERG_CERTIFICATE.Value }}"
    - secretName: docker-pull-pat
      secretNamespace: argocd
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          .dockerconfigjson: "{{ .DOCKER_PULL_PAT.Value }}"
    - secretName: git-credentials
      secretNamespace: argocd
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          username: "{{ .ARGOCD_IMAGER_UPDATER_GIT_USERNAME.Value }}"
          password: "{{ .ARGOCD_IMAGER_UPDATER_GIT_PAT.Value }}"
    - secretName: argocd-dex-authentik
      secretNamespace: argocd
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          dex.authentik.clientID: "{{ .ARGOCD_DEX_AUTHENTIK_CLIENT_ID.Value }}"
          dex.authentik.clientSecret: "{{ .ARGOCD_DEX_AUTHENTIK_CLIENT_SECRET.Value }}"
          # Argo Workflows client secret for Dex static client
          ARGO_WORKFLOWS_SSO_CLIENT_SECRET: "{{ .ARGO_WORKFLOWS_SSO_CLIENT_SECRET.Value }}"
    - secretName: argo-workflows-sso
      secretNamespace: argocd
      creationPolicy: "managed"
      template:
        includeAllSecrets: false
        data:
          client-id: "argo-workflows"
          client-secret: "{{ .ARGO_WORKFLOWS_SSO_CLIENT_SECRET.Value }}"
