apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical-secrets-operator
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-graz
        envSlug: prod
        secretsPath: "/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical-secrets-operator
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical-secrets-operator
      creationPolicy: "Orphan"
    - secretName: cloudflare-api-key
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          api-key: "{{ .CLOUDFLARE_API_KEY.Value }}"
