apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    # 1️⃣ Traefik CRDs (wichtig, zuerst installieren)
    - repoURL: https://traefik.github.io/charts
      chart: traefik-crds
      targetRevision: 37.2.0
      helm:
        valueFiles: []
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 37.2.0
      helm:
        valueFiles:
          - $values/eggenberg-reverse-proxy-cluster/argocd-apps-configuration/traefik/values.yaml
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      path: "eggenberg-reverse-proxy-cluster/argocd-apps-configuration/traefik"
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
