apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: NAME
  namespace: argocd
  labels:
    category: CATEGORY
spec:
  # yamllint disable rule:line-length
  project: default
  sources:
    - repoURL: CHART_REPO_URL
      targetRevision: CHART_VERSION
      chart: CHART_NAME
      helm:
        valueFiles:
          - $values/eggenberg-talos-cluster-1/argocd-apps-configuration/NAME/values.yaml
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      path: "eggenberg-talos-cluster-1/argocd-apps-configuration/NAME"
  destination:
    server: https://kubernetes.default.svc
    namespace: NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # yamllint enable rule:line-length
