apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
labels:
- pairs:
    app.kubernetes.io/environment: production
  includeTemplates: true
resources:
- namespace.yaml
- ../../base
components:
- ../../components/keda-ns-scoped
images:
- name: git.hauptmann.dev/philipphauptmann/contact-api
  newTag: 0.7.0
- name: git.hauptmann.dev/philipphauptmann/notifier-email
  newTag: 0.2.7
- name: git.hauptmann.dev/philipphauptmann/notifier-telegram
  newTag: 0.2.7
- name: git.hauptmann.dev/philipphauptmann/pmhme
  newTag: 0.15.0
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Rollout
    name: portfolio-app
- path: httproute-patch.yaml
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: portfolio-app-config
