apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
labels:
- pairs:
    app.kubernetes.io/environment: production
  includeTemplates: true
resources:
- namespace.yaml
- ../../base
images:
- name: dockerha08/pmhme
  newTag: 0.1.3
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Rollout
    name: portfolio-app
- path: httproute-patch.yaml
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: portfolio-app-config
