kubeProxyReplacement: true

k8sServiceHost: 192.168.0.65
k8sServicePort: 6443

loadBalancer:
  enabled: true

ipam:
  mode: kubernetes

operator:
  replicas: 1

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

nodeinit:
  enabled: true

rollOutCiliumPods: true
