apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.philippmhauptmann.me"
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-philippmhauptmann-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - argocd
                  - monitoring