apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.philippmhauptmann.me" # mehrere Subdomains erlauben
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-philippmhauptmann-tls
            kind: Secret
            group: ""