---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: istio-system
spec:
  parentRefs:
    - name: argocd-gateway
      namespace: istio-system
  hostnames:
    - "argo-reverse-proxy.philippmhauptmann.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
