---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-http-route
  namespace: argocd
spec:
  parentRefs:
    - name: ingress-gateway
      namespace: istio-system
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - "argo-rp.philippmhauptmann.me"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Strict-Transport-Security
                value: "max-age=31536000; includeSubDomains"
              - name: X-Frame-Options
                value: "DENY"
              - name: X-Content-Type-Options
                value: "nosniff"
              - name: X-XSS-Protection
                value: "1; mode=block"
      backendRefs:
        - name: argocd-server
          namespace: argocd
          port: 80
