apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: pmhme
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: false  # Image Updater handles dev
    - stage: test
      autoPromotionEnabled: true   # Auto-promote from dev when healthy
    - stage: production
      autoPromotionEnabled: false  # Manual approval
