apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: pmhme
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/mainman94/multi-k8s-infra
        writeBranch: main
        kustomize:
          images:
            - image: docker.io/dockerha08/pmhme
              path: eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/production
    argoCDAppUpdates:
      - appName: pmhme-portfolio-prod
        appNamespace: argocd
