apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: pmhme
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/mainman94/multi-k8s-infra
        writeBranch: main
        kustomize:
          images:
            - image: docker.io/dockerha08/pmhme
              path: eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/test
    argoCDAppUpdates:
      - appName: pmhme-portfolio-test
        appNamespace: argocd
  verification:
    analysisTemplates:
      - name: portfolio-http-check
    args:
      - name: service-name
        value: portfolio-service
      - name: namespace
        value: portfolio-test
