# yamllint disable rule:line-length
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: portfolio-updater
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: pmhme-portfolio
      images:
        - alias: portfolio
          imageName: dockerha08/pmhme
          commonUpdateSettings:
            updateStrategy: semver
            allowTags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
            forceUpdate: false
            pullSecret: pullsecret:argocd/docker-pull-pat
  writeBackConfig:
    method: "git:secret:argocd/git-credentials"
    gitConfig:
      repository: "https://github.com/mainman94/multi-k8s-infra"
      branch: "main"
      writeBackTarget: "kustomization:/eggenberg-reverse-proxy-cluster/argocd-apps-configuration/pmhme/overlays/production"
# yamllint enable rule:line-length
