apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portfolio-app-pdb
  namespace: portfolio
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "portfolio-app"
  unhealthyPodEvictionPolicy: IfHealthyBudget
