ingress:
  enabled: false
persistence:
  enabled: true
  storageClass: "longhorn"
  #accessMode: ReadWriteOnce
nscd:
  enabled: true
resources:
  limits:
    cpu: 16m
    memory: 572Mi
  requests:
    cpu: 12m
    memory: 380Mi
