ingress:
  enabled: true
  className: cilium
  hosts:
    - host: uptime.hauptmann.dev
      paths:
        - path: /
          pathType: Prefix
    - host: status.hauptmann.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudflare-origin-cert
      hosts:
        - uptime.hauptmann.dev
        - status.hauptmann.dev
persistence:
  enabled: true
  storageClass: "longhorn"
  #accessMode: ReadWriteOnce
nscd:
  enabled: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
