# yamllint disable rule:line-length
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-http-add-on
  namespace: argocd
  labels:
    category: scaling
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda-add-ons-http
      targetRevision: 0.16.0
      helm:
        valueFiles:
          - $values/eggenberg-talos-cluster-1/argocd-apps-configuration/keda-http-add-on/values.yaml
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      path: eggenberg-talos-cluster-1/argocd-apps-configuration/keda-http-add-on
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    # yamllint enable rule:line-length
