apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubernetes-sigs/gateway-api
      targetRevision: v1.4.0
      path: "config/crd/standard"
      directory:
        recurse: true
    - repoURL: https://github.com/mainman94/multi-k8s-infra
      targetRevision: HEAD
      path: "eggenberg-reverse-proxy-cluster/argocd-apps-configuration/gateway-api"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
